name: Day15-Capstone-CICD

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Application
        run: |
          zip -r deployment.zip . \
          -x "*.git*" \
          -x "node_modules/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload Artifact to S3
        run: |
          aws s3 cp deployment.zip s3://day15-capstone-artifacts/deployment.zip

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name day15-codedeploy-app \
            --deployment-group-name day15-deployment-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=day15-capstone-artifacts,bundleType=zip,key=deployment.zip
